name: "Build Expo App for release branch"
on:
  push:
    branches:
      - production
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Build iOS app
        run: eas build --non-interactive --platform=ios
