name: deploy terraform - nonprod

on:
  push:
    branches:
      - releases/nonprod

jobs:
  terraform:
    name: Terraform
    environment: nonprod
    defaults:
      run:
        shell: bash

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # https://stackoverflow.com/a/64195658
    # and https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
    - name: construct short docker image tag from git sha
      run: echo "IMAGE_TAG=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: construct .tfvars
      run: |-
        echo 'app_name="${{vars.APP_NAME}}"' >> .tfvars
        echo 'autoscaling_max="${{vars.AUTOSCALING_MAX || "5"}}"' >> .tfvars
        echo 'autoscaling_min="${{vars.AUTOSCALING_MIN || "2"}}"' >> .tfvars
        echo 'db_deletion_protection=${{vars.DB_DELETION_PROTECTION || "true"}}' >> .tfvars
        echo 'db_tier="${{vars.DB_TIER || "db-g1-small" }}"' >> .tfvars
        echo 'gcp_project_id="${{vars.GCP_PROJECT_ID}}"' >> .tfvars
        echo 'gcp_project_number="${{vars.GCP_PROJECT_NUMBER}}"' >> .tfvars
        echo 'image_tag="${{env.IMAGE_TAG}}"' >> .tfvars
        echo 'region="${{vars.GCP_REGION}}"' >> .tfvars
        echo 'use_dummy_appserver=${{vars.USE_DUMMY_APPSERVER || "false"}}' >> .tfvars
        cat .tfvars

    - name: auth to gcp
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TF_PROVISIONER_SVC_ACCOUNT_KEY_JSON }}
        service_account: 'terraform-provisioner@moz-fx-future-products-nonprod.iam.gserviceaccount.com'

    - name: init cloud sdk
      uses: google-github-actions/setup-gcloud@v1

    - name: auth docker
      # note: it's important to have the regional domain here for auth to succeed
      # XXX use location var
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: pull latest image for cache
      continue-on-error: true
      # XXX use vars
      run: docker pull us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:latest

    - name: build and push image
      # DRY_r4703 docker name and paths
      # XXX use vars
      run: |-
        docker build --file=dockerfiles/appserver --target appserver_prod -t us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:${{ env.IMAGE_TAG }} -t us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:latest --cache-from us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:latest .
        docker push us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:${{ env.IMAGE_TAG }}
        docker push us-central1-docker.pkg.dev/moz-fx-future-products-nonprod/boilertest1-repo1/appserver:latest

    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
        terraform_wrapper: false

    - name: terraform init
      working-directory: ./terraform/nonprod
      run: terraform init --backend-config="bucket=${{vars.BACKEND_TF_STATE_BUCKET}}"

    - name: terraform plan
      working-directory: ./terraform/nonprod
      run: terraform plan -no-color -input=false -out=tfplan -var-file=.tfvars

    - name: terraform apply
      working-directory: ./terraform/nonprod
      run: terraform apply -no-color -input=false -var-file=.tfvars tfplan

    - name: terraform outputs
      working-directory: ./terraform/nonprod
      run: terraform output -var-file=.tfvars


